language: objective-c
compiler:
  - clang

branches:
  only:
    - master

before_install:
  - export LANG=en_US.UTF-8

script: xctool -project Project/Vision.xcodeproj -scheme Debug -sdk iphonesimulator7.1 build analyze test
